### ISSUE TITLE
Could not install the project

### ISSUE THREAD

**Issue by marceepoonu** [DmitryGaravsky/AutoClosingMessageBox#11]
Visual Studio (which I was using for the very first time) gave me the error messages below.
Any suggestions would be much appreciated.

Here's what Visual Studio said:

Install-Package AutoClosingMessageBox -Version 1.0.0.3

Attempting to gather dependency information for package 'AutoClosingMessageBox.1.0.0.3' with respect to project 'AutoClosingMessageBox', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 524 ms
Attempting to resolve dependencies for package 'AutoClosingMessageBox.1.0.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'AutoClosingMessageBox.1.0.0.3'
Resolved actions to install package 'AutoClosingMessageBox.1.0.0.3'
Retrieving package 'AutoClosingMessageBox 1.0.0.3' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/autoclosingmessagebox/1.0.0.3/autoclosingmessagebox.1.0.0.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/autoclosingmessagebox/1.0.0.3/autoclosingmessagebox.1.0.0.3.nupkg 82ms
Installed AutoClosingMessageBox 1.0.0.3 from https://api.nuget.org/v3/index.json with content hash ERfNspmGrdJdSCzFbTyQKhAepH1Ktx5JfFZ8Imz4+TkBp7VslqkZ9EXFvijB9OExhe3d6geX1RcJbJ2+RKjPGg==.
Install failed. Rolling back...
Package 'AutoClosingMessageBox.1.0.0.3' does not exist in project 'AutoClosingMessageBox'
Package 'AutoClosingMessageBox.1.0.0.3' does not exist in folder 'E:\Apps\Powershell\Programs\AutoClosingMessageBox-master\AutoClosingMessageBox-master\packages'
Executing nuget actions took 858 ms
Install-Package : Could not install package 'AutoClosingMessageBox 1.0.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package AutoClosingMessageBox -Version 1.0.0.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.9950358
PM>

**Comment by DmitryGaravsky** [comment]
As far as I can see you've tried to use the latest version of AutoClosingMessageBox under the `.NETFramework,Version=v4.8`,
but the latest version of AutoClosingMessageBox package is designed to be used with the NET6+.
You can either use the previous version of this package or compile from sources.
