### ISSUE TITLE
missing function 

### ISSUE THREAD

**Issue by andreas-fe** [DmitryGaravsky/AutoClosingMessageBox#12]
First of all, thanks for this great project.
It was easy to include it in my application via NuGet.

But for my application one feature is missing, to bring the MessageBox top most in the front.
With the default MessageBox its the oprion "MessageBoxOptions.ServiceNotification".
Is it also possible to integrate this option in the AutoClosingMessageBox, or is there another way that the  message boxes are displayed in the foreground?

**Comment by DmitryGaravsky** [comment]
Hi!

Thank you for your interest.

You can specify the message box options via the Factory feature:

```cs
var messageBoxAsServiceNotification = AutoClosingMessageBox.Factory(
        showMethod: (caption, buttons) =>
            MessageBox.Show(this, "To be or not to be?", caption, buttons, MessageBoxIcon.Question,
            , MessageBoxDefaultButton.Button1, MessageBoxOptions.ServiceNotification), // options use
        caption: "The question"
    );
messageBoxAsServiceNotification .Show(); // showing 
```

The Factory feature is specially designed to provide access either to any existing or future features of the standard message box
without any restrictions and without affecting current API of AutoClosingMessageBox.
