### ISSUE TITLE
Automessagebox not focused when it shows

### ISSUE THREAD

**Issue by schizoidcock** [DmitryGaravsky/AutoClosingMessageBox#13]
This is working as expected but there is just one bug, the message box doesn't lock when it pop ups in front, and sometimes it goes behind the main form, it actually doesn't lock itself like message box does normally.

**Comment by schizoidcock** [comment]
could we have any fix for it soon?

**Comment by DmitryGaravsky** [comment]
Hi, and at first, thank you for your interest!

>it actually doesn't lock itself like message box does normally.

there is no any "custom" message-box behind, rather than standard/normal one. Could you please provide a small example that demonstrates problematical behavior?

**Comment by schizoidcock** [comment]
i mean if you have the actual form1 for example and you trigger the automessagebox event, the automessage box doesnt pop up sometimes on front of the form1 and you can actually move the form1, minimize it or resize it because it is not locking it, that doesnt happen when you trigger a messagebox event.

**Comment by DmitryGaravsky** [comment]
Hi

As i already mentioned the `AutoClosingMessageBoxis` is just a wrapper above the standard/normal one and all the approaches and behavior should be the same.
Thus, thinking of issue you described, I recommend you to specify the `owner` parameter explicitly when showing the message box:
```cs
public partial class Form1 : Form {
    public Form1() {
        InitializeComponent();
    }
    void onShowMessageBtnClick(object sender, EventArgs e){
        AutoClosingMessageBox.Show(owner: this, caption: "Hello, World!"); // show with owner
    }
}
```
If issue you described still exist, please provide me with a small example that clearly demonstrates the problematical behavior.

Thanks
