### ISSUE TITLE
Open multiple boxes at the same time

### ISSUE THREAD

**Issue by Alichegini12** [DmitryGaravsky/AutoClosingMessageBox#15]
hi
I am writing a code that may need to show several messages to the user in a short period of time
But now the messages are shown one after the other
How do I solve this problem?
Thanks

**Comment by DmitryGaravsky** [comment]
Hello and thank you for the question.
The MessageBox itself is designed to be a blocking. So if you want to show several messages simultaneously you should consider another solutions like [toast notifications](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-notifications-overview) or alerts. 
There are many implementations but from my experience I can recommend you those from DevExpress:
[Alert Windows](https://docs.devexpress.com/WindowsForms/114565/controls-and-libraries/messages-notifications-and-dialogs#alert-windows). They also provides a [Toast Notification Manager](https://docs.devexpress.com/WindowsForms/17020/controls-and-libraries/messages-notifications-and-dialogs/toast-notification-manager) as a solution for toasts from WinForms/Wpf application.

**Comment by Alichegini12** [comment]
Thank you very much for your reply
You helped a lot
