### ISSUE TITLE
How i can change the template from the message box ?

### ISSUE THREAD

**Issue by PEQSPC** [DmitryGaravsky/AutoClosingMessageBox#16]
Can i change the template from the message box  ?
How i can do that ?

Here?
![Screenshot 2024-09-03 160141](https://github.com/user-attachments/assets/40f4fe7d-ee89-4e4b-8bbc-06144a6edb3d)

**Comment by DmitryGaravsky** [comment]
Hi!

Thank you for your interest.

>Can i change the template from the message box ?

I believe your question is related to the WPF platform. Just to clarify, the AutoClosingMessageBox is a wrapper around the standard system message box (whether it's WPF or WinForms, it doesn't matter), so UI customization is not possible. However, we can talk about customizing and extending its behavior.

You can customize the message box options via the Factory feature. For example:

```cs
var messageBoxAsServiceNotification = AutoClosingMessageBox.Factory(
        showMethod: (caption, buttons) =>
            MessageBox.Show(this, "To be or not to be?", caption, buttons, MessageBoxIcon.Question,
            , MessageBoxDefaultButton.Button1, MessageBoxOptions.ServiceNotification), // options use
        caption: "The question"
    );
messageBoxAsServiceNotification .Show(); // showing 
```
The Factory feature is designed to provide access to any existing or future features of the standard message box, without any restrictions and without affecting the current API of AutoClosingMessageBox.
