### ISSUE TITLE
Compatibility with .net framework version 3.5

### ISSUE THREAD

**Issue by amol-kute** [DmitryGaravsky/AutoClosingMessageBox#2]
Will it support older .net versions like .net framework 3.5 and so?

**Comment by DmitryGaravsky** [comment]
I have addressed this issue by adding the separate build configuration based on AutoClosingMessageBox.Net3.5.csproj/AutoClosingMessageBox.Net3.5.sln which are powered by the .Net Framework 3.5 Client profile. The source code is also cleaned up for compliance.
