### ISSUE TITLE
Support for Icons

### ISSUE THREAD

**Issue by MassimoZambelli** [DmitryGaravsky/AutoClosingMessageBox#3]
Is it possible to use ( in the button enumeration) also the 
MsgBoxStyle.Information
MsgBoxStyle.Critical
MsgBoxStyle.Exclamation
MsgBoxStyle.Question
like in the standard messagebox?

Thank You
MZ

**Comment by DmitryGaravsky** [comment]
Hi,

Thank you for your question.

This functionality is already supported via the `AutoClosingMessageBox.Factory` method:

```cs
var toBeOrNotToBeQuestion = AutoClosingMessageBox.Factory(
        showMethod: (caption, buttons) =>
            MessageBox.Show(this, "To be or not to be?", caption, buttons, MessageBoxIcon.Question),
        caption: "The question"
    );
if(DialogResult.Yes == toBeOrNotToBeQuestion.Show(
                            timeout: 2500,
                            buttons: MessageBoxButtons.YesNo,
                            defaultResult: DialogResult.Yes)) {
    // to be
}
else {
    // or not
}
```
As you can see from the code snippet above you can use the `showMethod` parameter to get full control on MessageBox showing.

Please try this solution, and let me know your results.
