### ISSUE TITLE
Make the countdown visible

### ISSUE THREAD

**Issue by Andrealavoro** [DmitryGaravsky/AutoClosingMessageBox#4]
Hi!

Your AutoCloseMessageBox is great.

I have a little request for improvement: since the message window is timed but the user does not know it, would it be possible, perhaps on the button that has in focus, to put a small countdown?
This would allow the user to notice that the message box has a limited confirmation time.
![Immagine](https://user-images.githubusercontent.com/71023131/92612680-61fc8780-f2ba-11ea-9e5c-cf23c713dc25.png)

Many thanks in advance.

**Comment by DmitryGaravsky** [comment]
Hi and thanks for your kind words!
 
I agreed with you that this capability would be useful. 
And maybe, I could bring myself to go there, but no ETA though

**Comment by Dims-M** [comment]
Добрый вечер. 
А не подскажите реализована такая функция(отчета о закрытии)??

**Comment by DmitryGaravsky** [comment]
Добрый!

> функция(отчета о закрытии)

К сожалению я не вполне понял, что значит "отчет о закрытии",  - по описании звучит как event...
Сможете продемонстрировать в псевдо-коде как это видится на вашей стороне?

**Comment by Dims-M** [comment]
Извиняюсь не совсем корректно написал. 
Хотел написать "Отсчет о закрытии" а написал "отчет о закрытии" )))
выводится на форме сообщения обратный отсчет в секунда после завершения которого форма сообщения закроется?
PS
Он только для Windows Form?? Для WPF надо будет переделовать?

**Comment by DmitryGaravsky** [comment]
Добрый день. 
>выводится на форме сообщения обратный отсчет в секунда после завершения которого форма сообщения закроется?

Нет, функциональность не реализована.

>Он только для Windows Form?? Для WPF надо будет переделовать?

Да, для WinForms. Не было задачи никогда сделать это для WPF.

Технически, в WPF просто другой namespace для самого MsgBox и его запчастей (MessageBoxButtons и т.п.), 
т.е. сама идея абсолютно также применима к WPF как и к WinForms.

Надо будет на досуге выложить рядом версию для WPF.

**Comment by Dims-M** [comment]
Спасибо большое за быстрый отвеет. Подписался на обновления )))

**Comment by DmitryGaravsky** [comment]
JFI - на досуге запилил таки Wpf/WinForms дуализм, заодно и докинул поддержку .Net5.
детали тут: [.NET5 support and Win/WPF](https://github.com/DmitryGaravsky/AutoClosingMessageBox/commit/b125b2bc849bf625617e9f6b7d15a066f0a95a2c)

**Comment by Princyaarthy** [comment]
Hi Dmitry,
Thank you for AutoCloseMessageBox package .its really useful. I'd like to get an info on this countdown implementation; is it included in your package?

**Comment by DmitryGaravsky** [comment]
Hi, 
today I have added the countdown functionality
See the [.NET6 + CountDown Feature](https://github.com/DmitryGaravsky/AutoClosingMessageBox/commit/01ecdb3155dc1c4db12634af15aaf58d4374296f) for details.

You can use the countdown using the following codesnippet:

```
AutoClosingMessageBox.Show("Hello, World!", timeout: 5000, showCountDown: true);
```
