### ISSUE TITLE
Focus?

### ISSUE THREAD

**Issue by bazzacad** [DmitryGaravsky/AutoClosingMessageBox#5]
How do I give it focus so it shows up on top of other windows?

**Comment by DmitryGaravsky** [comment]
Hi,

Thank you for your question.

The AutoClosingMessageBox is only the wrapper to the [MessageBox](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messagebox?view=netcore-3.1) class, thus **you can use the same approaches** here:
 - use the `IWin32Window owner` parameter to put the AutoClosingMessageBox on top of the specific application window:
```cs
AutoClosingMessageBox.Show(this, "Hello, World!");
```
- use the same parameter with topmost-trick to put the AutoClosingMessageBox on top of the entire application:
```cs
AutoClosingMessageBox.Show(new Form(){ TopMost = true }, "Hello, World!");
```

 - use the `AutoClosingMessageBox.Factory` method to show the MessageBox in a custom manner:
```cs
AutoClosingMessageBox.Factory(
        showMethod: (caption, buttons) =>
            return MessageBox.Show(this, 
                "You did not enter a server name. Cancel this operation?",
                 caption, buttons,
                MessageBoxIcon.Question, 
                MessageBoxDefaultButton.Button1, 
                MessageBoxOptions.ServiceNotification); // <<<<<<<< trick
        caption: "No Server Name Specified"
    ).Show(buttons: MessageBoxButtons.YesNo);
```

Please try this solution, and let me know your results.

Related Links: 
[Why isn't MessageBox TopMost?](https://stackoverflow.com/questions/16105097/why-isnt-messagebox-topmost)
[MessageBoxOptions Enum](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxoptions?view=netcore-3.1)
