### ISSUE TITLE
Default functionality not working 

### ISSUE THREAD

**Issue by lv1986** [DmitryGaravsky/AutoClosingMessageBox#8]
Hi, 
I have installed library using nuget package. After installation I have found that some of default features are not working. Message box is opening but not closing after time interval specified. I have tried following: 

```
AutoClosingMessageBox.Show("Hello, World!");
AutoClosingMessageBox.Show("Text",null, 1000);
AutoClosingMessageBox.Show("Text", string.Empty, 1000);
```
If i provide caption then it is working fine (Auto close after time interval)
`AutoClosingMessageBox.Show("Text", "caption", 1000);`

**Comment by DmitryGaravsky** [comment]
Hi, thank you for your message!
I have tried to reproduce this issue by using the latest version of the AutoClosingMessageBox library and failed:
 - all of your examples work as expected (message boxes are opening and then closing after 1000 ms).
 
 Could you please build the library from sources by using one of the following solutions:
  -  [AutoClosingMessageBox.Net5.Wpf.sln](https://github.com/DmitryGaravsky/AutoClosingMessageBox/blob/master/AutoClosingMessageBox.Net5.Wpf.sln) solution for WPF
  -  [AutoClosingMessageBox.Net5.Win.sln](https://github.com/DmitryGaravsky/AutoClosingMessageBox/blob/master/AutoClosingMessageBox.Net5.Win.sln) solution for WinForms
  
and let me know your results?
