### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TeaTiMe08** [DmitryGaravsky/AutoClosingMessageBox#9]
Hi Dimitry,

i want to use your library in one oy my commercially used project.
So i ask for permission to do so.
At best you'd add a (non-GPL.x) license to your project so more people can use it.

With best regards!

**Comment by DmitryGaravsky** [comment]
Hi 

>I want to use your library in one of my commercially used projects.
>So I ask for permission to do so.

Thank you for your interest! Of course, I see no problem with using my library in your project.

>At best you'd add a (non-GPL.x) license to your project so more people can use it.

I really appreciate your suggestion, thus I have added [MIT](https://github.com/DmitryGaravsky/AutoClosingMessageBox/blob/master/LICENSE.TXT) license.

Thanks
